#!/usr/bin/env bash
#  a Bash script that transfers a file from our client to a server

PATH_TO_FILE=$1
SERVER_IP=$2
USERNAME=$3
PATH_TO_SSH_KEY=$4

if [ $# -lt 4 ]
    then
        echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    else
        scp -i "$PATH_TO_SSH_KEY" -o StrictHostKeyChecking=no  "$PATH_TO_FILE" "$USERNAME@$SERVER_IP:~/"
fi
