#!/usr/bin/env bash
# Install nginx

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo apt-get -y install curl
echo "Hello World!" || /var/www/html/index.html
service nginx restart
